### ISSUE TITLE
Bug: Pasting Checklist Item Over Checklist or List Item Over List Item Causes Removal of Checklist/List Indicator

### ISSUE THREAD

**Issue by pjkaufman** [platers/obsidian-linter#801]
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

When pasting a checklist item or items onto other checklist items, if you select to include the checklist indicator it will remove both checklist indicators leaving the resulting text as a no longer valid checklist indicator.

The same applies to the prevent double list indicators on paste

## How to Reproduce

Paste `- [x] item 1` onto the `- [x] ` from the following markdown:

``` markdown
- [x] some item here
- [ ] other checklist item
```

The issue with double list indicators is the same.
## Expected Behavior

The checklist indicator from the paste should be retained in this case.

Expected output if applicable:

``` markdown
- [x] some item here
- [ ] other checklist item
```

would become
``` markdown
- [x] item 1
- [ ] other checklist item
```

## Screenshots

NA

## Device

- [x] Desktop
- [x] Mobile

## Additional Context

Passing in the selected text should take care of this.

**Comment by pjkaufman** [comment]
This has been fixed and should be on master. It will go out in the next release.
